module.exports=function(grunt){
    //configuration
    grunt.initConfig({
        //options to plugins, reference to files
        uglify:{
            js:{
                files:[{
                    src:'js/app.js',
                    dest:'dist/js/app.js'
                },
                {
                    src:'js/init.js',
                    dest:'dist/js/init.js'
                },
                {
                    src:'js/materialize.min.js',
                    dest:'dist/js/materialize.min.js'
                }
            ]
            }
        },
        htmlmin:{
            html:{
                files:[
                    {
                        src:'index.html',
                        dest:'dist/index.html'},
                    {
                        src:'pages/Events.html',
                        dest:'dist/pages/Events.html'
                    },
                    {
                        src:'pages/Fallback.html',
                        dest:'dist/pages/Fallback.html'
                    },
                    {
                        src:'pages/Gallery.html',
                        dest:'dist/pages/Gallery.html'
                    }
                ]
            }
        },
        cssmin:{
            css:{
                files:[
                    {
                        src:'css/materialize.min.css',
                        dest:'dist/css/materialize.min.css'
                    },
                    {
                        src:'css/style.css',
                        dest:'dist/css/style.css'
                    }
                ]
            }
        },
        copy:{
            copyfiles:{
                files:[
                    {
                        src:'manifest.json',
                        dest:'dist/manifest.json'
                    },
                    {
                        src:'LICENSE',
                        dest:'dist/LICENSE'
                    },
                    {
                        src:'404.html',
                        dest:'dist/404.html'
                    },
                    {
                        src:'img/icons/*.png',
                        dest:'dist/img/icons'
                    }
                ]
            }
        }
    });


    //load plugins
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-htmlmin');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-contrib-copy');
    //registering
   grunt.registerTask('run',['uglify:js','htmlmin:html','cssmin:css','copy:copyfiles']);
  
};